### ISSUE TITLE
Sample App should be Consistent with App Developer's Guide

### ISSUE THREAD

**Issue by skliper** [nasa/sample_app#1]
Originated by Dave (135 on babelfish)

The sample_app provided with the cFE is not consistent with the example app documented in the Application Developer's Guide. The App Developer's Guide should documented recommended styles and practices. Similarly the sample_app should implement them. I don't think Sample App needs to cover all of the potential app features like Critical Data Stores, Child Tasks, etc. Just the basics to get someone started.

**Comment by skliper** [comment]
Comment transferred from ​#280 from Dave -
QQ found in cFE 4.0.1
I found a version of qq app and based on file prologue comments it was synched with what's in the app developer's guide. I have not verified that this is still the case.

**Comment by avan989** [comment]
I can do this.
