### ISSUE TITLE
Remove function names from comments (where not useful)

### ISSUE THREAD

**Issue by skliper** [nasa/sample_app#111]
**Is your feature request related to a problem? Please describe.**
Function names in comments (end of function comment, function header comment) historically have been poorly maintained.

Example:
https://github.com/nasa/sample_app/blob/0d11d9e7b1edf339c33870340524916f81a5dd95/fsw/src/sample_app.c#L393
https://github.com/nasa/sample_app/blob/0d11d9e7b1edf339c33870340524916f81a5dd95/fsw/src/sample_app.c#L425

**Describe the solution you'd like**
Remove redundant information (these end of function comments and name from the header).

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by ShobhitSamuelSingh** [comment]
Hi, I want to work on this issue.

**Comment by skliper** [comment]
Yes, Yes, Yes.  With automated formatting applied to enforce consistent indentation I don't see much value in any of those comments.
