### ISSUE TITLE
Recommend using FcnCode (instead of CommandCode) terminology in the code

### ISSUE THREAD

**Issue by SpaceSteve121** [nasa/sample_app#167]
The current implementation of the sample app mixes terminology, [calling the field which identifies a command a `CommandCode`](https://github.com/nasa/sample_app/blob/bd4a5fe53c22246998b29eecf3cfa9c5c323f6cc/fsw/src/sample_app.c#L264)  whereas the CFE APIs call it a `FcnCode`.

Since this app is the starting point for many people, it might make sense to use consistent terminology. Since the CFE APIs call it a `FcnCode`, it seems like the code should too.

**Comment by thnkslprpt** [comment]
Note the same issue occurs in to_lab and ci_lab (I assume the functions were copied from one to the other when these lab apps were created, with the relevant adaptations being made).
![Screenshot 2022-10-19 10 15 30](https://user-images.githubusercontent.com/9024662/196568594-37c9b07c-ee2f-4fb7-800f-cc13847c900f.png)
