### ISSUE TITLE
systematic naming convention?

### ISSUE THREAD

**Issue by JustinGOSSES** [nasa/sample_app#2]
Can all the The Core Flight System (cFS) repositories follow a systematic naming convention with cFs-<name>?

Just 'sample_app' seems to pollute the namespace. Thank you.

**Comment by skliper** [comment]
Good suggestion and a change I would support.  Any NASA repo naming conventions would need to come from the NASA admins, and implemented by them.  GitHub.com/nasa lists github@lists.nasa.gov as a contact.

**Comment by JustinGOSSES** [comment]
I'm an admin and can make that change. If you're okay with it and you don't need to change anything elsewhere to avoid breakage, I'll go ahead and change it.

**Comment by skliper** [comment]
I'd suggest the first step would be to come up with a naming convention for the NASA repos to avoid namespace collisions.  Or if it's just "prepend all cFS related NASA repos with cFS" then I'd suggest getting concurrence from all the cFS related repo maintainers prior to implementing.  I only maintain the cFS Framework repos (~13 of them), there's apps and tools out there owned by others (likely 10-20 additional repos).  I'm all for the change as long as it's done to all the cFS repos at once, and it would break things temporarily for anyone who's cloned them or uses the cFS bundle (and the bundle would break until I fix it) but I could make the repo fixes to the ones I maintain fairly quickly.

**Comment by JustinGOSSES** [comment]
Thank for the context @skliper . Would you like to initiate that conversation with all the repo owners? I'm not familiar with cFS or who is involved. I can make the changes but shouldn't be coordinating.

**Comment by skliper** [comment]
Unfortunately I don't have the bandwidth to coordinate such a change at present.

**Comment by JustinGOSSES** [comment]
FYI - A repo whose name is changed won't break clones, at least not immediately.  When you attempt to push code back, you'll get a warning from git and then the push will go to the right spot. Github stops maintaining both names at some point, but it isn't immediately. I have other repos that I've renamed and continued contributing code without changing the name locally for quite some time.
