### ISSUE TITLE
Sample App has error counter and command counter reversed

### ISSUE THREAD

**Issue by jphickey** [nasa/sample_app#25]
**Describe the bug**
The SAMPLE_ReportHousekeeping function reports the error count and command count values reversed.

**To Reproduce**
Send a NOOP command, then report housekeeping, and see that the error count is in place of the the command count.

**Expected behavior**
The error count and command count should not be reversed.

**Code snips**

Inside `SAMPLE_ReportHousekeeping()`, it has:

```
    Sample_AppData.SAMPLE_HkTelemetryPkt.sample_command_error_count = Sample_AppData.CmdCounter;
    Sample_AppData.SAMPLE_HkTelemetryPkt.sample_command_count = Sample_AppData.ErrCounter;
```

**System observed on:**
Ubuntu 18.04 LTS 64-bit

**Additional context**
Actually discovered this when writing the unit test for the ReportHousekeeping function (#8), and the test case failed because the counters were backwards.

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment]
@jphickey Is the referenced commit ready for a pull request (or did I miss it)?
