### ISSUE TITLE
Build fails with deprecated cFE/OSAL elements removed

### ISSUE THREAD

**Issue by skliper** [nasa/sample_app#35]
**Describe the bug**
Build fails on 7 undeclared errors:
[Errors.txt](https://github.com/nasa/sample_app/files/4036322/Errors.txt)

**To Reproduce**
make OMIT_DEPRECATED=true prep (requires https://github.com/nasa/cFE/pull/457)

**Expected behavior**
Clean build

**System observed on:**
 - cFS Dev Server 2
 - OS: Ubuntu 18.04
 - Versions: mostly 6.7 (+ commit above)

**Reporter Info**
Jacob Hageman - NASA/GSFC

**Comment by skliper** [comment]
@dmknutsen could you prioritize this one?  Basically just needs to use the new defines.

**Comment by linayurkova** [comment]
Identified the same system issue:
Matrix settings for the second occurrence:
AMD64
Compiler: gcc C
BUILDTYPE=release OMIT_DEPRECATED=true
