### ISSUE TITLE
Apply code style

### ISSUE THREAD

**Issue by skliper** [nasa/sample_app#37]
**Is your feature request related to a problem? Please describe.**
Inconstant style

**Describe the solution you'd like**
See https://github.com/nasa/ci_lab/pull/30 and https://github.com/nasa/ci_lab/pull/28

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
Closed by accidental merge to `main`. Reopening
