### ISSUE TITLE
fails to build under Raspbian - alignment of pointers

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/sample_app#38]
**Describe the bug**
Trying to build under Raspbian, sample_app fails with "cast increases required alignment of target type" errors.

```
/home/pi/cFS/apps/sample_app/fsw/src/sample_app.c:365:25: error: cast increases required alignment of target type [-Werror=cast-align]
     CFE_SB_TimeStampMsg((CFE_SB_Msg_t *) &Sample_AppData.SAMPLE_HkTelemetryPkt);
                         ^
/home/pi/cFS/apps/sample_app/fsw/src/sample_app.c:366:20: error: cast increases required alignment of target type [-Werror=cast-align]
     CFE_SB_SendMsg((CFE_SB_Msg_t *) &Sample_AppData.SAMPLE_HkTelemetryPkt);
```

**To Reproduce**
Build on Raspbian.

**Expected behavior**
Should not cause warnings/errors.

**Code snips**

**System observed on:**
Raspberry Pi Zero W

**Additional context**

**Reporter Info**
Christopher.D.Knight@nasa.gov

**Comment by CDKnightNASA** [comment]
Note that CFE_SB_InitMsg() takes a void *, whereas TimeStampMsg and SendMsg take CFE_SB_MsgPtr_t. I'm guessing InitMsg should be updated to use CFE_SB_MsgPtr_t.

**Comment by jphickey** [comment]
See also nasa/cfe#440 about the API inconsistency here.

**Comment by jphickey** [comment]
The alignment warnings are the same general issue as in nasa/cfe#313.  If you want you can assign this to me and just turn off -Wcast-align in your build for now.
