### ISSUE TITLE
Suggest refactoring sample_app to more closely match "real" apps.

### ISSUE THREAD

**Issue by ejtimmon** [nasa/sample_app#45]
**Is your feature request related to a problem? Please describe.**
This ticket is not related to a problem.  This is a feature request to reorganize the sample app to more closely match "real" apps (namely the GSFC open source apps).  This would increase sample_app's value as a template.  In addition to providing a more realistic example, the organization of functions into files has implications for unit testing.

**Describe the solution you'd like**
1. Move command functions into a separate sample_app_cmds.c file.  
2. Move utility functions into a separate sample_app_utils.c file

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Elizabeth Timmons - NASA/GSFC

**Comment by jphickey** [comment]
In general I concur with this idea but please see pull request #43 prior to doing any additional refactoring.

Also - its been discussed in the past to put each command into a separate .c file, to eventually pave the way for commands to be included/excluded via compile-time configuration.  Not saying that it should necessarily go there now, but I do think it would be a good thing to consider.

**Comment by skliper** [comment]
I concur with eventually splitting commands into separate files for multiple reasons, I've found it beneficial in the past to organize more along the one "unit" per file model.
