### ISSUE TITLE
skeleton app

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/sample_app#50]
**Is your feature request related to a problem? Please describe.**
sample_app is great for showing a variety of capabilities that cFS provides to an application, but folks will likely come to sample_app thinking it's a good starting place for them to develop their new apps. I suggest we also have a "skeleton_app" either as a separate GIT repository (and referenced in the sample_app docs) or contained in the sample_app folder.

**Describe the solution you'd like**
a skeleton_app which has the barest of minimums to make it a valid cFS application.

**Additional context**
Add any other context about the feature request here.

**Requester Info**
Christopher.D.Knight@nasa.gov

**Comment by mprather** [comment]
This is a really good idea. The tutorials should also address the skeleton app as the primary example.
