### ISSUE TITLE
SAMPLE_ReportHousekeeping fails, likely due to nasa/cfe#674

### ISSUE THREAD

**Issue by skliper** [nasa/sample_app#64]
**Describe the bug**
UT failure, likely related to nasa/cfe#674:
```
[BEGIN] 05 SAMPLE_ReportHousekeeping
[ FAIL] 05.001 coveragetest_sample_app.c:391 - HkTelemetryMsg.Payload.CommandCounter (0) == 22
[ FAIL] 05.002 coveragetest_sample_app.c:395 - HkTelemetryMsg.Payload.CommandErrorCounter (0) == 11
[ PASS] 05.003 coveragetest_sample_app.c:401 - CFE_TBL_Manage() called
[  END] 05 SAMPLE_ReportHousekeeping TOTAL::3     PASS::1     FAIL::2      MIR::0      TSF::0      N/A::0
```

**To Reproduce**
Build and run unit tests at bundle level with nasa/cfe#674 included

**Expected behavior**
Tests pass

**Code snips**
N/A

**System observed on:**
 - Hardware: cFS Dev Server 3
 - OS: Ubuntu 18.04
 - Versions Bundle with nasa/cfe#674 included

**Additional context**
N/A

**Reporter Info**
Jacob Hageman - NASA/GSFC

**Comment by skliper** [comment]
@jphickey could you take this one, planning to fasttrack.  Either that or back out nasa/CFE#674 from this round (assuming it's the culprit) .

**Comment by jphickey** [comment]
Found this is due to the pkt length being 0 so the output packet isn't being copied out.
In here we need to call CFE_SB_InitMsg() and in the SB stub side we need to fix the reading of the length.

**Comment by jphickey** [comment]
Should I put this in a PR or go direct to IC?

**Comment by jphickey** [comment]
Nevermind - I just pushed direct to IC as a hotfix as you mentioned you wanted to fasttrack.  See commit 155a3e7

**Comment by jphickey** [comment]
See also nasa/cfe@6f06b16 for the CFE side of things.
