### ISSUE TITLE
sample_table.c -- relocate?

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/sample_app#70]
**Is your feature request related to a problem? Please describe.**
Tables are a component of applications that are expected to be customized by the user. The cFS build process supports this customization (for example, by creating `sample_defs/tables/cpu1_sample_table.c`). Currently `sample_table.c` is in `fsw/src` but everything else in `fsw/src` is not expected to be customized by the user.

I consider sample_app to be the "style template" for applications, so this should be clear not just for users of the sample_app but for folks who model their code on sample_app.

**Describe the solution you'd like**
I would like to see a clearer indication that `sample_table.c` is expected to be customized--whether it be relocated to a different folder (`fsw/tables`?) or possibly rename it to `sample_table.c.sample`?

**Requester Info**
Christopher.D.Knight@nasa.gov

**Comment by CDKnightNASA** [comment]
Would like CCB decision on this, thx.

**Comment by jphickey** [comment]
Yes - sample_table is the wrong place, it should be in a separate dir, not in `fsw/src`, as it is configuration, not code, and it is expected that a mission will customize its content by adding a file in "defs" directory.

Recommend `fsw/tables` as the pattern for example table files.  I believe this is what other apps use.
