### ISSUE TITLE
should sample_app be writing to syslog?

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/sample_app#72]
**Is your feature request related to a problem? Please describe.**
I thought that, generally, apps should be generating events on errors, not writing to syslog. However, if you look at, say SAMPLE_AppInit(), it writes to syslog for a number of error conditions.

**Describe the solution you'd like**
Re-write to generate events.

**Requester Info**
Christopher.D.Knight@nasa.gov

**Comment by jphickey** [comment]
I think its rather impractical to do every possible minor condition as an event.  Writing a string to a log file is far easier in many circumstances, particularly for the things that don't happen very often.

The syslog should be stored somewhere that it can be retrieved if necessary to diagnose off-nominal conditions, but I wouldn't say that _everything_ that could possibly go wrong has to have a unique event ID.

**Comment by CDKnightNASA** [comment]
> I think its rather impractical to do every possible minor condition as an event. Writing a string to a log file is far easier in many circumstances, particularly for the things that don't happen very often.
> 
> The syslog should be stored somewhere that it can be retrieved if necessary to diagnose off-nominal conditions, but I wouldn't say that _everything_ that could possibly go wrong has to have a unique event ID.

I was under the (mistaken?) impression that direct calls to syslog were discouraged as long as EVS was available...I'd like to get a feel from the CCB when syslog reporting is considered appropriate. (I'd actually be happier with less stringent requirement to use EVS but I understand the value EVS brings to a spacecraft environment.)

**Comment by jphickey** [comment]
Event IDs are sent to the ground as they occur, whereas syslog remains stored on the spacecraft and can only be read via special means (dump to file + transfer, etc).  So yeah, events are certainly more visible when in flight mode.  But they have much more baggage, too.  And in a debug mode where someone is looking at the console then they are both visible.  Syslog should still be accessible though, even in flight mode, it's just not as easy.

All I'm saying is I don't know of any hard rule (nor should there be one) about making absolutely everything an event.  During debug the Syslog is just as visible, which is where many of these off-nominal conditions are most likely to occur.   Once transitioned to flight mode things should be stable enough that many conditions become unlikely or impossible to happen.

It is at the developer's discretion to determine how likely certain conditions are to occur during flight mode and decide whether the condition is worth the extra baggage of an event ID.

**Comment by CDKnightNASA** [comment]
> Event IDs are sent to the ground as they occur, whereas syslog remains stored on the spacecraft and can only be read via special means (dump to file + transfer, etc). So yeah, events are certainly more visible when in flight mode. But they have much more baggage, too. And in a debug mode where someone is looking at the console then they are both visible. Syslog should still be accessible though, even in flight mode, it's just not as easy.
> 
> All I'm saying is I don't know of any hard rule (nor should there be one) about making absolutely everything an event. During debug the Syslog is just as visible, which is where many of these off-nominal conditions are most likely to occur. Once transitioned to flight mode things should be stable enough that many conditions become unlikely or impossible to happen.
> 
> It is at the developer's discretion to determine how likely certain conditions are to occur during flight mode and decide whether the condition is worth the extra baggage of an event ID.

With sample_app, it is writing to syslog when it fails to load the table. I think it will be a rare situation where the failure to load a table does not cause a failure of the app to load. Of course, CFE_TBL should/will/does generate events (see #607) and ES will (I believe) report events.

In these cases, why write to syslog at all as it is redundant with events and generally adding noise?

**Comment by jphickey** [comment]
> In these cases, why write to syslog at all as it is redundant with events and generally adding noise?

True - in _some_ cases a syslog message might be duplicating events from other apps.  But I think that's OK, as long as we don't go into information overload.

From a dev/debug perspective, more information is usually better than less, and the syslog might have more/additional context info.  One of the advantages of syslog messages vs. events is their free-form nature.  Event messages are supposed to conform to one specific (limited) format string, and furthermore one can enable "short form" events where the message isn't even included at all.  Syslog by comparison is totally free form, containing any information the developer thinks is relevant.  Changing an event format string is a big deal and needs buy-in with the ground system and many stakeholders, documentation updates, etc.  Syslog is more of a developer/debug tool and doesn't really leave the FSW, so it is just a matter of updating the code with the relevant info.

On a system like Linux that has a system-wide syslog daemon, I've found it incredibly useful to see what was happening not only with the app that had the problem, but all other apps that were running at the same time, even non-cFE daemons and such.
