### ISSUE TITLE
CMakeLists.txt not C++ friendly

### ISSUE THREAD

**Issue by jmahoney-dev** [nasa/sample_app#84]
**Describe the bug**
This might be out of scope of this project but when baselining off of sample_app to make other apps I have been able to write C++ code and extern "C" functions to run in the sample_app.c main file (or equivalent). Now that the CMakeLists.txt file does not have the "aux_source_directory(fsw/src APP_SRC_FILES)" and "add_cfe_app(sample_app APP_SRC_FILES)" lines, the C++ externed functions are not linked by the cmake build system. By explicitly saying "add_cfe_app(sample_app fsw/src/sample_app.c)" the link command won't pick up the necessary C++ symbols.  

**To Reproduce**
1. Create a C++ file in app src directory and make a function called "extern "C" void test() { printf("test\n") }"
2. Forward declare this test function in sample_app.c at the top by writing "void test()" 
3. Add "CXX" to the project() line in CMakeLists.txt
4. Call test() in sample_app.c somewhere where you know it will be called (init or main run loop) 
5. Build and run on target 

**Expected behavior**
Target should have an error similar to "undefined symbol" when dynamically loading/linking the sample_app during cFS startup/initialization 

**System observed on:**
 - Linux Ubuntu 18.04, Intel i7 VxWorks 7 target
 - OS: Ubuntu 18.04 and VxWorks 7

**Reporter Info**
Joe Mahoney - LTA Research

**Comment by skliper** [comment]
The use of `aux_source_directory` is discouraged (see modern CMake documentation).  Recommendation is to simply add the files you need in the add_cfe_app line or create a list of all the files and pass the list in.  `add_cfe_app(myapp fsw/src/sample_app.c fsw/src/mycode.cpp)`  Feel free to reopen if this doesn't address your need.
