### ISSUE TITLE
Unit test fails when VER_2 headers are used

### ISSUE THREAD

**Issue by skliper** [nasa/sample_app#87]
**Describe the bug**
Event test strings are different when the MsgId size changes, but test looks for explict message:
https://github.com/nasa/sample_app/blob/c1348d6fcb7f911396c9928a1779ddad6fe0c339/fsw/src/sample_app.c#L274-L277

https://github.com/nasa/sample_app/blob/c1348d6fcb7f911396c9928a1779ddad6fe0c339/unit-test/coveragetest/coveragetest_sample_app.c#L290

https://github.com/nasa/sample_app/blob/c1348d6fcb7f911396c9928a1779ddad6fe0c339/unit-test/coveragetest/coveragetest_sample_app.c#L549

!VER_2 = `0xffff`, VER_2 =`0xffffffff` (or capitalized based on the format string)

**To Reproduce**
Set MESSAGE_FORMAT_IS_CCSDS_VER_2, build and run unit tests.

**Expected behavior**
Unit tests should pass with either configuration

**Code snips**
See above.

**System observed on:**
 - Hardware: cFS Dev VM
 - OS: Ubuntu 18.04
 - Versions: main bundle

**Additional context**
None

**Reporter Info**
Jacob Hageman - NASA/GSFC

**Comment by skliper** [comment]
Probably easiest to just remove the explicit string check (pass in blank).

**Comment by jphickey** [comment]
Yeah, this is why I don't like to check derived in UT.  My recommendation is (and has always been) to only check the specific outputs of the unit under test, which in this case is the format string (i.e. "SAMPLE: invalid command packet,MID = 0x%x") not the fully formed output string, which is dependent on a number of factors outside the control of the unit under test.

IIRC there were some folks specifically _wanting_ to do this type of test and hence why it was included in sample_app example.

A possible compromise would be to only check the format string.

**Comment by skliper** [comment]
Note with nasa/cfe#880 the reported error is now consistent since message ID base type is uint32.
