### ISSUE TITLE
Sample tests should not use CFE_SB_InitMsg stub to initialize a message

### ISSUE THREAD

**Issue by asgibson** [nasa/sample_app#89]
**Describe the bug**
CFE_SB_InitMsg is used in coveragetest_sample_app.c to initialize a message so that the CFE_SB_SendMsg stub has a valid message to use.  This is not proper form. A unit test should not be calling a stub to provide this setup.  Stubs are to be used by production code in place of the actual calls in order for a unit test to isolate the code under test, they should not be used as utility functions for the unit tests.

**To Reproduce**
See Code snips.

**Expected behavior**
Provide a ut_assert utility that has the functionality to create a cFS message for use by a unit test.

**Code snips**
https://github.com/nasa/sample_app/blob/c1348d6fcb7f911396c9928a1779ddad6fe0c339/unit-test/coveragetest/coveragetest_sample_app.c#L414-L417

**System observed on:**
RHEL 7.6

**Additional context**
This is related to a cFE issue.  If the CFE_SB_SendMsg stub worked as described in there, most situations where this is used would not even be required (just verifying the message pointer instead of the actual message itself).
https://github.com/nasa/cFE/issues/818

**Reporter Info**
Alan Gibson NASA GSFC/587

**Comment by skliper** [comment]
Note you can check how many times a stub was called in your test.  See UT_GetStubCount().  Doesn't solve the address problem, but you can tell how many times a unit under test calls a stub.  I'll check to see how many things in the framework break if we update SendMsg to return the address.
