### ISSUE TITLE
String checks in UT should check only the spec/format string, not the fully rendered text.

### ISSUE THREAD

**Issue by jphickey** [nasa/sample_app#97]
**Describe the bug**
As the comment in the code suggests, the "fully-rendered" text is really a derived output that depends on a lot of external factors.  It isn't a direct output of the unit under test.

As an example, the unit test is currently getting thrashed around due to a message ID check due to the fact that there is no specific text that is always "correct" here.  

It broke when updated to 32 bit (#87), attempted to fix in #94, which only broke the original case (v1 header).

**To Reproduce**
Run unit test using v1 (16-bit) message IDs.
**Currently failing in the integration-candidate branch**

**Expected behavior**
Tests should pass.

**System observed on:**
Ubuntu 20.04 and Travis-CI (current integration candidate).

**Additional context**
Recommendation is to only check the SPEC STRING (`0x%x`) which will be the same regardless of what the "invalid msgid" value actually is.  That's all that really matters.

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment]
Note #94 does not break v1 when merged with nasa/cFE#880.
